# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo_z7_20_base_20202/zybo_z7_20_base_20202.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202 || ORIG_REF_NAME==zybo_z7_20_base_20202} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_processing_system7_0_0/zybo_z7_20_base_20202_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_processing_system7_0_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_processing_system7_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_clk_wiz_0_0/zybo_z7_20_base_20202_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_clk_wiz_0_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_proc_sys_reset_0_0/zybo_z7_20_base_20202_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_0_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_proc_sys_reset_0_1/zybo_z7_20_base_20202_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_0_1 || ORIG_REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_proc_sys_reset_1_0/zybo_z7_20_base_20202_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_1_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_xlconcat_0_0/zybo_z7_20_base_20202_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_xlconcat_0_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_xlconcat_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_axi_gpio_0_0/zybo_z7_20_base_20202_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_axi_gpio_0_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_xbar_0/zybo_z7_20_base_20202_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_xbar_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_xbar_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_auto_pc_0/zybo_z7_20_base_20202_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_auto_pc_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_auto_pc_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_ps7_0_axi_periph_0/zybo_z7_20_base_20202_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_ps7_0_axi_periph_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_rst_ps7_0_50M_0/zybo_z7_20_base_20202_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_rst_ps7_0_50M_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_axi_gpio_1_0/zybo_z7_20_base_20202_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_axi_gpio_1_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_20202/ip/zybo_z7_20_base_20202_PmodGPIO_0_0/zybo_z7_20_base_20202_PmodGPIO_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_20202_PmodGPIO_0_0 || ORIG_REF_NAME==zybo_z7_20_base_20202_PmodGPIO_0_0} -quiet] -quiet

# XDC: /media/cole/XilinxShare/camera_design_vivado/camera_design_vivado/camera_design_vivado.gen/sources_1/bd/zybo_z7_20_base_20202/zybo_z7_20_base_20202_ooc.xdc
